// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Message.proto

#include "Message.pb.h"
#include "Message.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* Processing_method_names[] = {
  "/Processing/Compute",
};

std::unique_ptr< Processing::Stub> Processing::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Processing::Stub> stub(new Processing::Stub(channel, options));
  return stub;
}

Processing::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Compute_(Processing_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Processing::Stub::Compute(::grpc::ClientContext* context, const ::aMessage& request, ::aMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::aMessage, ::aMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Compute_, context, request, response);
}

void Processing::Stub::async::Compute(::grpc::ClientContext* context, const ::aMessage* request, ::aMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::aMessage, ::aMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Compute_, context, request, response, std::move(f));
}

void Processing::Stub::async::Compute(::grpc::ClientContext* context, const ::aMessage* request, ::aMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Compute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::aMessage>* Processing::Stub::PrepareAsyncComputeRaw(::grpc::ClientContext* context, const ::aMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::aMessage, ::aMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Compute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::aMessage>* Processing::Stub::AsyncComputeRaw(::grpc::ClientContext* context, const ::aMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncComputeRaw(context, request, cq);
  result->StartCall();
  return result;
}

Processing::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Processing_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Processing::Service, ::aMessage, ::aMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Processing::Service* service,
             ::grpc::ServerContext* ctx,
             const ::aMessage* req,
             ::aMessage* resp) {
               return service->Compute(ctx, req, resp);
             }, this)));
}

Processing::Service::~Service() {
}

::grpc::Status Processing::Service::Compute(::grpc::ServerContext* context, const ::aMessage* request, ::aMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


