// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
#define _WIN32_WINNT 0x601
#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Message_2eproto;
class aMessage;
struct aMessageDefaultTypeInternal;
extern aMessageDefaultTypeInternal _aMessage_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::aMessage* Arena::CreateMaybeMessage<::aMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class aMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aMessage) */ {
 public:
  inline aMessage() : aMessage(nullptr) {}
  ~aMessage() override;
  explicit PROTOBUF_CONSTEXPR aMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  aMessage(const aMessage& from);
  aMessage(aMessage&& from) noexcept
    : aMessage() {
    *this = ::std::move(from);
  }

  inline aMessage& operator=(const aMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline aMessage& operator=(aMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const aMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const aMessage* internal_default_instance() {
    return reinterpret_cast<const aMessage*>(
               &_aMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(aMessage& a, aMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(aMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(aMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  aMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<aMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const aMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const aMessage& from) {
    aMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(aMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aMessage";
  }
  protected:
  explicit aMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFirstFieldNumber = 1,
  };
  // repeated float First = 1;
  int first_size() const;
  private:
  int _internal_first_size() const;
  public:
  void clear_first();
  private:
  float _internal_first(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_first() const;
  void _internal_add_first(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_first();
  public:
  float first(int index) const;
  void set_first(int index, float value);
  void add_first(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      first() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_first();

  // @@protoc_insertion_point(class_scope:aMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > first_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// aMessage

// repeated float First = 1;
inline int aMessage::_internal_first_size() const {
  return _impl_.first_.size();
}
inline int aMessage::first_size() const {
  return _internal_first_size();
}
inline void aMessage::clear_first() {
  _impl_.first_.Clear();
}
inline float aMessage::_internal_first(int index) const {
  return _impl_.first_.Get(index);
}
inline float aMessage::first(int index) const {
  // @@protoc_insertion_point(field_get:aMessage.First)
  return _internal_first(index);
}
inline void aMessage::set_first(int index, float value) {
  _impl_.first_.Set(index, value);
  // @@protoc_insertion_point(field_set:aMessage.First)
}
inline void aMessage::_internal_add_first(float value) {
  _impl_.first_.Add(value);
}
inline void aMessage::add_first(float value) {
  _internal_add_first(value);
  // @@protoc_insertion_point(field_add:aMessage.First)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
aMessage::_internal_first() const {
  return _impl_.first_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
aMessage::first() const {
  // @@protoc_insertion_point(field_list:aMessage.First)
  return _internal_first();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
aMessage::_internal_mutable_first() {
  return &_impl_.first_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
aMessage::mutable_first() {
  // @@protoc_insertion_point(field_mutable_list:aMessage.First)
  return _internal_mutable_first();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
